#!/bin/sh
echo "Compilling [$@] ..."
if [[ $# == "1" ]]; then
	set -- "" "$1"
fi;
counter=1
read -r firstLine < "$2"
if [[ $firstLine == "#!"* ]]; then
    ((counter++))
fi
file=$(cat $2 | sed '1d')
tmp_name=.tmp_$(uuidgen)
cat > $tmp_name.c <<EOF
#include <libc.h>
int main(int argc, char	**argv)
{
ON_STARTUP
#line $counter "$2"
$file
}
EOF
cc $(sed -e 's/^"//' -e 's/"$//' <<<"$1") $tmp_name.c -o $tmp_name.out && echo "done " && echo "________"
shift
shift
rm $tmp_name.c
./$tmp_name.out $@
rm $tmp_name.out
